name: Sync

on:
  schedule:
    - cron: '0 0,8,16,20 * * *'

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Trigger Sync
        shell: bash
        env:
          TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          curl -L --header "Content-Type: application/json" \
            --request POST \
            --data '{"token":"reTurn.0f.th3.jed1!is_The-B3ST_star-waRs-moviE!"}' \
            https://www.pattern-analyzer.app/api/sync
