name: Sync

on:
  schedule:
    - cron: '0 0,8,16,20 * * *'

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Trigger Sync
        shell: bash
        env:
          TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"token":"$TOKEN"}' \
            https://pattern-analyzer.app/api/sync
